name: raptchat
description: "Companion app for the LoRaptor device."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_speed_dial: ^7.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  dynamic_color: ^1.7.0
  file_picker: ^8.1.7
  uuid: ^4.5.1
  flutter_svg: ^2.0.17
  build_runner: ^2.4.15
  pointycastle: ^3.9.1
  asn1lib: ^1.5.9
  crypto: ^3.0.6
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.6
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  image_cropper: ^9.0.0
  flutter_blue_plus: ^1.35.3
  test: ^1.25.15
  collection: ^1.19.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/langs/
    - assets/logo.svg
    - assets/fonts/
  fonts:
    - family: Zain
      fonts:
        - asset: assets/fonts/Zain-Regular.ttf
          weight: 500
        - asset: assets/fonts/Zain-Light.ttf
          weight: 400
        - asset: assets/fonts/Zain-LightItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Zain-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Zain-Bold.ttf
          weight: 800
        - asset: assets/fonts/Zain-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Zain-Black.ttf
          weight: 900

    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-VariableFont_wght.ttf
        - asset: assets/fonts/Overpass-Italic-VariableFont_wght.ttf
          style: italic

flutter_icons:
  android: true
  ios: false  # Since you only need an APK
  image_path: "assets/icon.png"  # Your converted PNG
  adaptive_icon_foreground: "assets/icon.png"  # For Android adaptive icons
  adaptive_icon_background: "#ffffff"  # Or use a PNG background